const races = {
    Other: "Other",
    Air_Elemental: "Air Elemental",
    Banshee: "Banshee",
    Barbed_Devil: "Barbed Devil",
    Basilisk: "Basilisk",
    Bearded_Devil: "Bearded Devil",
    Black_Dragon: "Black Dragon",
    Black_Pudding: "Black Pudding",
    Blue_Dragon: "Black Dragon",
    Bugbear: "Bugbear",
    Bulette: "Bulette",
    Centaur: "Centaur",
    Chasme: "Chasme",
    Chimera: "Chimera",
    Construct: "Construct",
    Cyclops: "Cyclops",
    Dinosaur: "Dinosaur",
    Dragonborn: "Dragonborn",
    Dretch: "Dretch",
    Drider: "Drider",
    Drow: "Drow",
    Duergar: "Duergar",
    Dwarf: "Dwarf",
    Earth_Elemental: "Earth Elemental",
    Elf: "Elf",
    Ettin: "Ettin",
    Fire_Dwarf: "Fire Dwarf",
    Fire_Elemental: "Fire Elemental",
    Fire_Giant: "Fire Giant",
    Frog_of_War: "Frog of War",
    Frost_Giant: "Fire Giant",
    Ghoul: "Ghoul",
    Gnoll: "Gnoll",
    Gnome: "Gnome",
    Goblin: "Goblin",
    Green_Dragon: "Green Dragon",
    Harpy: "Harpy",
    Hell_Hound: "Hell Hound",
    Hill_Giant: "Hill Giant",
    Hobgoblin: "Hobgoblin",
    Human: "Human",
    Inexorable: "Inexorable",
    Kobold: "Kobold",
    Manticore: "Manticore",
    Mantis_Knight: "Mantis Knight",
    Minotaur: "Minotaur",
    Mynconoid: "Mynconoid",
    Nightmare: "Nightmare",
    Ogre: "Ogre",
    Orc: "Orc",
    Owlbear: "Owlbear",
    Purple_Worm: "Purple Worm",
    Red_Dragon: "Red Dragon",
    Roc: "Roc",
    Salamander: "Salamander",
    Shadow: "Shadow",
    Shadow_Demon: "Shadow Demon",
    Shambling_Mound: "Shambling Mound",
    Skeleton: "Skeleton",
    Sprite: "Sprite",
    Stone_Devil: "Stone Devil",
    Stone_Giant: "Stone Giant",
    Time_Raider: "Time Raider",
    Treant: "Treant",
    Triton: "Triton",
    Troll: "Troll",
    Virtue: "Virtue",
    Vrock: "Vrock",
    Water_Elemental: "Water Elemental",
    Wight: "Wight",
    Wraith: "Wraith",
    Wyvern: "Wyvern",
    Zombie: "Zombie"
  };
  
  export default races;