const traits = {
    0 : "AAUUUGH!!!" ,
    1 : "Adaptable" ,
    2 : "Aerial Bombardment" ,
    3 : "Amphibious" ,
    4 : "Arcadian" ,
    5 : "Archers" ,
    6 : "Armor Osmosis" ,
    7 : "Armored Carapace" ,
    8 : "Barbs" ,
    9 : "Battle Hymn" ,
    10 : "Beacon of Courage" ,
    11 : "Beacon of Order" ,
    12 : "Better than One" ,
    13 : "Big" ,
    14 : "Blanket Fire" ,
    15 : "Bless the Rains" ,
    16 : "Blinding" ,
    17 : "Burning" ,
    18 : "Burrow" ,
    19 : "Chaos Vulnerability" ,
    20 : "Charge" ,
    21 : "Chorus of Victory" ,
    22 : "Close Enough" ,
    23 : "Close Range" ,
    24 : "Cloud of Darkness" ,
    25 : "Collateral Damage" ,
    26 : "Consume" ,
    27 : "Corrode" ,
    28 : "Corrosive Breath" ,
    29 : "Create Dead" ,
    30 : "Cunning Ambush" ,
    31 : "Damage Resistant" ,
    32 : "Daylight Weakness" ,
    33 : "Dead" ,
    34 : "Defy Gravity" ,
    35 : "“Dig!”" ,
    36 : "Dire Hyena Mounts" ,
    37 : "Directed Fire" ,
    38 : "Disruptive" ,
    39 : "Draconic Ancestry" ,
    40 : "Dragonkin" ,
    41 : "Drone" ,
    42 : "Elf-shot" ,
    43 : "Embiggen" ,
    44 : "Eternal" ,
    45 : "Ethereal" ,
    46 : "Expert Fade" ,
    47 : "Fade" ,
    48 : "Fast Siege Weapon (Heavy)" ,
    49 : "Fast Siege Weapon" ,
    50 : "Fearless" ,
    51 : "Fearsome" ,
    52 : "Feast" ,
    53 : "Find Path" ,
    54 : "Fire Blast" ,
    55 : "Fire Breath" ,
    56 : "Fire Immunity" ,
    57 : "First Strike" ,
    58 : "Flaming Weapons" ,
    59 : "Frame" ,
    60 : "Fury" ,
    61 : "Goblin Battle Platform" ,
    62 : "Guerrillas" ,
    63 : "Gulp" ,
    64 : "Hallucinatory Spores" ,
    65 : "Hard Hats" ,
    66 : "Harpoon" ,
    67 : "Harriers" ,
    68 : "Harrowing" ,
    69 : "Hellfire Cannons" ,
    70 : "Heroes of the Myriad Worlds" ,
    71 : "Holy" ,
    72 : "Hop" ,
    73 : "Implacable" ,
    74 : "Indistinct" ,
    75 : "Inexorable" ,
    76 : "Inspire Fear" ,
    77 : "Into the Breach" ,
    78 : "Invisibility" ,
    79 : "It Will Burn As We Burn" ,
    80 : "Jaunt" ,
    81 : "Lightning Breath" ,
    82 : "Lightning" ,
    83 : "Load the Bones!" ,
    84 : "Made from Magic" ,
    85 : "Magic Resistant" ,
    86 : "Magical Adepts" ,
    87 : "Maneuver: Break Them" ,
    88 : "Maneuver: Detonate" ,
    89 : "Maneuver: Focused Aim" ,
    90 : "Maneuver: Outflank" ,
    91 : "Maneuver: Repair" ,
    92 : "Maneuver: Scamp-ede of Corgis" ,
    93 : "Maneuver: Strafe" ,
    94 : "Maneuver: Testudo" ,
    95 : "Maneuver: “Evasive Maneuvers!”" ,
    96 : "Maneuver: “Fire!!”" ,
    97 : "Maneuver: “Hold the Line!”" ,
    98 : "Maneuver: “Lancers! Flank Them!”" ,
    99 : "Maneuver: “Land and Charge!”" ,
    100 : "Maneuver: “Prey on the Weak" ,
    101 : "Maneuver: “Spit Upon Their Horns" ,
    102 : "Mass Protection Against Evil" ,
    103 : "Master Elf-shot" ,
    104 : "Max Burn!" ,
    105 : "Meld" ,
    106 : "Mobile Battery" ,
    107 : "Mobile" ,
    108 : "Nature’s Bond" ,
    109 : "None" ,
    110 : "Now This Is an AAAUUUGH!" ,
    111 : "Noxious Fog" ,
    112 : "Offensive" ,
    113 : "Only the Smart Survive" ,
    114 : "Owlbears Can’t Fly?!" ,
    115 : "Pack Tactics" ,
    116 : "Pike Training" ,
    117 : "Plagued" ,
    118 : "Point Blank" ,
    119 : "Poisonous" ,
    120 : "Pool of Soul’s Blood" ,
    121 : "Power Word: Annihilate" ,
    122 : "Quadruped" ,
    123 : "Ram Riders" ,
    124 : "Reckless" ,
    125 : "Reflector" ,
    126 : "Regenerate" ,
    127 : "Relentless" ,
    128 : "Ride the Lightning" ,
    129 : "Rime" ,
    130 : "Rock!" ,
    131 : "Rockbreaker" ,
    132 : "Rolling Thunder" ,
    133 : "Rush" ,
    134 : "Savage" ,
    135 : "Scourge of the Wild" ,
    136 : "Scouts" ,
    137 : "Screech" ,
    138 : "Shock Troops" ,
    139 : "Shock and Awe" ,
    140 : "Siege Engine" ,
    141 : "Siege Weapon (Heavy)" ,
    142 : "Siege Weapon" ,
    143 : "Slam" ,
    144 : "Smoke Screen" ,
    145 : "Solar Flare" ,
    146 : "Soporific Spores" ,
    147 : "Sow Chaos" ,
    148 : "Spike Shot" ,
    149 : "Split" ,
    150 : "Spores" ,
    151 : "Stalwart" ,
    152 : "Stinky" ,
    153 : "Stone" ,
    154 : "Stoneskin" ,
    155 : "Strength in Numbers" ,
    156 : "Strength of the Wilds" ,
    157 : "Stupid" ,
    158 : "Stygian Orb" ,
    159 : "Survival of the Fittest" ,
    160 : "Swords of the Dragon Lord" ,
    161 : "Terror-dactyls" ,
    162 : "To the Death" ,
    163 : "Veterans of a Thousand Wars" ,
    164 : "Wail" ,
    165 : "Warbred" ,
    166 : "Wave" ,
    167 : "Whirlwind" ,
    168 : "Wireless" ,
    169 : "You Follow!" ,
    170 : "You Will Be Upgraded" ,
};
  
  export default traits;